/**
 * Roblox font families (FontFace file names / legacy Font enum) → the font the UI preview
 * draws with. Most of Roblox's fonts are open-licensed and bundled as-is (public/roblox-fonts,
 * generated by scripts/fetch-roblox-fonts.ts). Roblox-only fonts (Gotham, Builder Sans, a few
 * legacy faces) use the closest open font, and the preview says so.
 */

interface FontChoice {
  /** Bundled family (declared as "Rbx {family}" in roblox-fonts.css). */
  family: string;
  /** Set when this isn't the actual Roblox font. */
  substituteFor?: string;
  /** Minimum weight to draw with (e.g. Fredoka One is Fredoka's heavy cut). */
  minWeight?: number;
}

const SAME = (family: string): FontChoice => ({ family });
const SUB = (family: string, original: string): FontChoice => ({ family, substituteFor: original });

const FONTS: Record<string, FontChoice> = {
  SourceSansPro: SAME("Source Sans 3"),
  SourceSans: SAME("Source Sans 3"),
  Montserrat: SAME("Montserrat"),
  GothamSSm: SUB("Montserrat", "Gotham"),
  Gotham: SUB("Montserrat", "Gotham"),
  BuilderSans: SUB("Montserrat", "Builder Sans"),
  BuilderMono: SUB("Roboto Mono", "Builder Mono"),
  Oswald: SAME("Oswald"),
  FredokaOne: { family: "Fredoka", minWeight: 600 },
  Fredoka: SAME("Fredoka"),
  JosefinSans: SAME("Josefin Sans"),
  Roboto: SAME("Roboto"),
  RobotoCondensed: SAME("Roboto Condensed"),
  RobotoMono: SAME("Roboto Mono"),
  Creepster: SAME("Creepster"),
  ComicNeueAngular: SUB("Comic Neue", "Comic Neue Angular"),
  ComicNeue: SAME("Comic Neue"),
  TitilliumWeb: SAME("Titillium Web"),
  SpecialElite: SAME("Special Elite"),
  Nunito: SAME("Nunito"),
  Arimo: SAME("Arimo"),
  Arial: SUB("Arimo", "Arial"),
  LegacyArial: SUB("Arimo", "Legacy (Arial)"),
  LuckiestGuy: SAME("Luckiest Guy"),
  Bangers: SAME("Bangers"),
  PressStart2P: SAME("Press Start 2P"),
  Michroma: SAME("Michroma"),
  Zekton: SUB("Michroma", "SciFi (Zekton)"),
  AmaticSC: SAME("Amatic SC"),
  DenkOne: SAME("Denk One"),
  Fondamento: SAME("Fondamento"),
  GrenzeGotisch: SAME("Grenze Gotisch"),
  IndieFlower: SAME("Indie Flower"),
  Jura: SAME("Jura"),
  Kalam: SAME("Kalam"),
  Merriweather: SAME("Merriweather"),
  PatrickHand: SAME("Patrick Hand"),
  PermanentMarker: SAME("Permanent Marker"),
  Sarpanch: SAME("Sarpanch"),
  Ubuntu: SAME("Ubuntu"),
  Inconsolata: SUB("Inconsolata", "Code"),
  Balthazar: SUB("Balthazar", "Fantasy"),
  AccanthisADFStd: SUB("Bodoni Moda", "Bodoni (Accanthis)"),
  Guru: SUB("EB Garamond", "Garamond (Guru)"),
  HighwayGothic: SUB("Overpass", "Highway"),
};

export interface ResolvedFont {
  /** CSS font-family value. */
  css: string;
  weight: number;
  italic: boolean;
  /** What Roblox would draw, when the preview uses something else. */
  substituteFor: string | null;
}

/** Resolves a manifest font key (e.g. "GothamSSm", "asset:12187365364") for drawing. */
export function resolveFont(key: string, weight: number, italic: boolean): ResolvedFont {
  const choice = FONTS[key];
  if (!choice) {
    const label = key.startsWith("asset:") ? `custom font ${key.slice(6)}` : key;
    return { css: `"Rbx Source Sans 3", system-ui, sans-serif`, weight, italic, substituteFor: label };
  }
  return {
    css: `"Rbx ${choice.family}", system-ui, sans-serif`,
    weight: Math.max(weight, choice.minWeight ?? 0),
    italic,
    substituteFor: choice.substituteFor ?? null,
  };
}

/** CSS `font` shorthand for measuring/drawing. */
export function fontShorthand(font: ResolvedFont, size: number): string {
  return `${font.italic ? "italic " : ""}${font.weight} ${size}px ${font.css}`;
}
